# Hello Notebook! 
Why use a notebook?


*   Run scripts of code and it save all the variables until you terminate it.
*   Write code, test it and proceed without having to start over (especially usefull when you have to run time consuming tasks)
*   Combine text with code, so that you can add more comments and details about the code you write. You can even add pictures, comment on the results and even create a full report of your work. 

# Google Colab

An online platform from google that lets you run interactive notebooks. 



In a Notebook except for python code or text you can also run cmd commands. You can use these commands for example to install a python librady.

In [7]:
!pwd

/home/alkinoos/Documents/3d geometry/lab0


In [8]:
# !pip install open3d

# Python code in notebooks

* Matrices as Lists
* Matrix multiplication


In [9]:
# create a list of random numbers
import random 

def create_random_matrix(x, y):
    m = []
    for i in range(x):
      col = [] 
      for j in range(y):
        col.append(random.random())
      m.append(col)
    return m

# create a 3x4 matrix
create_random_matrix(3, 4) # see that we don't have to use print

[[0.261558645513849,
  0.11369556221398791,
  0.678393285842335,
  0.14179249301623487],
 [0.76798136772329,
  0.6978233494076946,
  0.41002854440342906,
  0.12231121151944857],
 [0.858005501972336,
  0.8906988254080855,
  0.5972696785680269,
  0.8771545331648442]]

In [10]:
mat = create_random_matrix(4, 3)
mat

[[0.47373234680450604, 0.20060020448704696, 0.6231948228856172],
 [0.05527651340998563, 0.12293233547799709, 0.8537651938010385],
 [0.14327813227152908, 0.6556056534062356, 0.7904534319001656],
 [0.25587079657396405, 0.6039008904579104, 0.024712462699837623]]

# Matrix Multiplication

In [11]:
def matmul(a, b):
    
    #check that the multiplication is actually possible
    assert len(a[0]) == len(b)
    
    #number of rows and columns
    n, m = len(a), len(b[0])
    
    #reserving memory for the output
    result = [[0] * m for _ in range(n)]
    
    #iterating over rows and columns
    for i in range(n):
        for j in range(m):
            #result is the dot product between the ith row of a and the jth column of b
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

mat1 = create_random_matrix(2, 10)
mat2 = create_random_matrix(10, 2)

mat = matmul(mat1, mat2)
mat

[[1.0432767491454347, 1.9581334485448256],
 [1.4307837271924835, 2.2313268991562953]]

# Monitor your process
When you have to iterate over a process for a long time, it is important to know how your process is following. One way to do this is to use a progress bar.  

For this you can use tqdm:


```
from tqdm import tqdm

for i in tqdm(range):
  # you iterative process
```

In [12]:
from tqdm import tqdm
import time

In [13]:
# make 100 matrix multiplications of 100x100 matrices
iterations = 10

mat1 = create_random_matrix(100, 1000)
mat2 = create_random_matrix(1000, 100)

start_time = time.time()

for i in tqdm(range(iterations)):
    matmul(mat1, mat2)

end_time = time.time()

total_time = end_time - start_time
avg_time_per_multiplication = total_time / iterations
print("Total time per multiplication: {:.6f} seconds".format(total_time))
print("Average time per multiplication: {:.6f} seconds".format(avg_time_per_multiplication))

100%|██████████| 10/10 [00:12<00:00,  1.23s/it]

Total time per multiplication: 12.357289 seconds
Average time per multiplication: 1.235729 seconds


This process is very slow and its not affordable in large applications. 

Solution....

# NumPy

# Array Creation #

In [15]:
import numpy as np

#From list
a1 = np.array([1, 2, 3], dtype=np.float64)

#Random numbers
np.random.seed(42)
a2 = np.random.random((3, 3))

#Equally spaced numbers
a3 = np.linspace(0, 1, 10)

#Serial numbers
a4 = np.arange(10)

print(a1)
print(a2)
print(a3)
print(a4)

[1. 2. 3.]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0 1 2 3 4 5 6 7 8 9]


# Array Manipulation

In [ ]:
#---Array shape---
# print(a1.shape)
# print(a2.shape)
# print(a3.shape)

#---Array data type---
# print(a1.dtype)
# print(a2.dtype)
# print(a3.dtype)

#---Reshaping an array---
a3 = a3.reshape(2, 5)
print(a3)

#---Indexing---
a = np.random.random((100, 3))

#get element 0, 0
print(a[0,0])

#get first row
print(a[0,:], a[0,:].shape)

#get first column
print(a[:,0].shape)

#get elements 10 through 20 of the first column
print(a[10:20, 0].shape)

# Array Operations

In [ ]:
mat1 = np.eye(3) * 2
mat2 = np.linspace(0,1,9).reshape(3, 3)
vec1 = np.arange(3)
vec2 = np.random.random((3, 1))
# print(mat1)
# print(mat2)


#matrix addition
mat3 = mat1 + mat2
# print(mat3)

#Hadamard product (element-wise multiplication)
mat3 = mat1 * mat2
# print(mat3)

#Matrix multiplication
mat3 = mat1 @ mat2
# print(mat3)

#Multiplication by a scalar
mat3 = mat1 * 0.3

#Matrix - vector multiplication
mat3 = mat1 @ vec1
# print(mat3.shape)
# print(mat3)

#broadcasting
mat3 = (mat1 + 1) * vec2
# print(mat1 + 1, mat1.shape)
# print(vec2, vec2.shape)
# print(mat3)

In [ ]:
# importing libraries
import numpy as np
import open3d as o3d

In [ ]:
# Define the matrices to be multiplied
a = np.random.random((100, 100))
b = np.random.random((100, 100))


# Perform N matrix multiplications and measure the time it takes
start_time = time.time()

for i in tqdm(range(iterations)):
    c = a @ b

end_time = time.time()


# Print the average time per multiplication
total_time = end_time - start_time
avg_time_per_multiplication = total_time / iterations

print("Total time per multiplication: {:.6f} seconds".format(total_time))
print("Average time per multiplication: {:.6f} seconds".format(avg_time_per_multiplication))

# *Open3D*

Loading a mesh file

In [ ]:
# load an object from the open3d library - used only to get the path of the mesh file
armadillo_mesh = o3d.data.ArmadilloMesh()
path = armadillo_mesh.path
path

In [ ]:
# loading a mesh from a file
mesh = o3d.io.read_triangle_mesh(path)
o3d.visualization.draw_plotly([mesh])

## Create a Point Cloud from a mesh file
Use the vertices of the mesh to construct a point cloud

In [ ]:
# get the vertices of the mesh
vertices = mesh.vertices
type(vertices)

In [ ]:
# transform the vertices to numpy format
vertices = np.asarray(vertices)
type(vertices)

In [ ]:
vertices.shape

Create a point cloud from a set of points

In [ ]:
# create an empty point cloud
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(vertices)

o3d.visualization.draw_plotly([pcd])
# zoom in to see the points

In [ ]:
# a more object oriented way to create the point cloud from numpy data
pcd = o3d.utility.Vector3dVector(vertices)
pcd = o3d.geometry.PointCloud(pcd) # pass the points at the constructor

o3d.visualization.draw_plotly([pcd])

## Point Cloud downsampling

Keep 1024 random points for the point cloud

* Shuffle the points of the point cloud (search documentation)
* Use indexing to keep the first 1024 points

In [ ]:
np.random.shuffle(vertices)
vertices = vertices[:1024, :]

In [ ]:
# visualize the new downsampled point cloud
pcd = o3d.utility.Vector3dVector(vertices)
pcd = o3d.geometry.PointCloud(pcd) # pass the points at the constructor

o3d.visualization.draw_plotly([pcd])

## Paint the points of the point cloud depending on their position across the x-axis

In [ ]:
colors = np.zeros_like(vertices)
colors[:,0] = vertices[:,0]

pcd.colors = o3d.utility.Vector3dVector(colors)

o3d.visualization.draw_plotly([pcd])

In [ ]:
colors = np.zeros_like(vertices)
x = vertices[:,0]
x = (x - x.min())/ (x.max() - x.min())
colors[:,0] = x

pcd.colors = o3d.utility.Vector3dVector(colors)

o3d.visualization.draw_plotly([pcd])